version: '3.6'

services:
  kafka-healthcheck:
    image: image-hub.despexds.net/kafka-healthcheck:0.0.1
    command: ["kafka-healthcheck"]
    container_name: kafka-healthcheck
    #restart: always
    ports:
      - '9290:9290'
    networks:
      - kafka_network
    environment:
      - HEALTHCHECK_KAFKA_HOST=localhost
      - HEALTHCHECK_LOG_LEVEL=WARNING
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  kafka_network:
    driver: bridge
